version: '2.1'
services:
  entity:
    build: regexp-entity
    image: arsenal-docker.cse.sri.com/regexp-entity:latest
    environment:
      HOST: entity
      PORT: 8080
    ports:
      - 8060:8080
  nl2cst:
    build: ../seq2seq
    image: arsenal-docker.cse.sri.com/arsenal-nl2cst:latest
    volumes:
      - ./models:/opt/models:ro
    environment:
      NL2CST_HOST: nl2cst
      NL2CST_PORT: 8080
      MODEL_ROOT: /opt/models/2021-06-24T1637-07_41c4757_REgrammar-re_2021-06-24T1816-07
    ports:
      - 8070:8080
  ui:
    build:
      context: regexp-ui
      dockerfile: docker/Dockerfile
    image: arsenal-docker.cse.sri.com/regexp-ui:latest
    environment:
      HOST: ui
    ports:
      - 8080:8080
  reformulate:
    build:
      context: ../
      dockerfile: regexp/generate-reformulate/Dockerfile
    image: arsenal-docker.cse.sri.com/regexp-reformulate:latest
    ports:
      - 8090:8080
